# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true 
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'tomcat-devsecops-connection'
    sourceFolder: '$(Agent.BuildDirectory)/'
    contents: '**/*.war'
    targetFolder: '/var/lib/tomcat9/weapps/'
    readyTimeout: '20000'
    flattenFolders: true
- task: SSH@0
  inputs:
    sshEndpoint: 'tomcat-devsecops-connection'
    runOptions: 'inline'
    inline: |
      /var/lib/tomcat9/conf/shutdown.sh
      /var/lib/tomcat9/conf/startup.sh
    readyTimeout: '20000'