# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'webapp-project'
    scanPath: '/home/vsts/work/1/s/target'
    format: 'HTML'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true 
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonartoken'
    scannerMode: 'Other'
- task: SonarQubeAnalyze@5
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'tomcat-devsecops-connection'
    sourceFolder: '/home/vsts/work/1/s/target'
    contents: '**/*.war'
    targetFolder: '/var/lib/tomcat9/webapps'
    readyTimeout: '20000'
